### ISSUE TITLE
异步日志在rollFile的时候导的崩溃

### ISSUE THREAD

**Issue by arhlong** [chenshuo/muduo#267]
今天发现产生了coredump，用gdb查看了一下，信息如下：

(gdb) bt
#0  0x0000003af34690e6 in setbuffer () from /lib64/libc.so.6
#1  0x00000000004f6110 in muduo::LogFile::rollFile() () at /home/suyl/project/muduo-1.0.9/muduo/base/LogFile.cc:101
#2  0x00000000004f541c in muduo::AsyncLogging::threadFunc() () at /home/suyl/project/muduo-1.0.9/muduo/base/AsyncLogging.cc:101
#3  0x00000000004faf6a in muduo::detail::startThread(void*) () at /usr/local/include/boost/function/function_template.hpp:771
#4  0x0000003af3807aa1 in start_thread () from /lib64/libpthread.so.0
#5  0x0000003af34e8aad in clone () from /lib64/libc.so.6

使用的muduo版本是v1.0.9

**Comment by chenshuo** [comment]
贴能复现你说的现象的可编译运行的完整代码以及完整复现步骤。
