### ISSUE TITLE
echo_client  demo core dump

### ISSUE THREAD

**Issue by youngqqcn** [chenshuo/muduo#497]
- Ubuntu 20.04
- gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- linux
```
linux version 5.8.0-34-generic (buildd@lcy01-amd64-015) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #37~20.04.2-Ubuntu SMP Thu Dec 17 14:53:00 UTC 2020
```
- muduo:
```
commit 0697be7fe16a9d24e64f0198254e7ecc037dc621 (HEAD -> master, origin/master, origin/HEAD)
Author: Ran Millier <z861983448@gmail.com>
Date:   Sat Oct 10 09:04:52 2020 +0800
```

```cpp
#include <stdio.h>
#include <muduo/net/TcpClient.h>
#include <muduo/base/Logging.h>
#include <muduo/net/EventLoop.h>

using namespace muduo;
using namespace muduo::net;

class EchoClient : noncopyable
{

public:
    EchoClient(EventLoop *pLoop, const InetAddress &addr)
        : _m_pLoop(pLoop),
          _m_client(_m_pLoop, addr, "client")
    {
        _m_client.setConnectionCallback(std::bind(&EchoClient::onConnection, this, _1));
        _m_client.setMessageCallback(std::bind(&EchoClient::onMessage, this, _1, _2, _3));
    }

    void connect()
    {
        _m_client.connect();
    }

private:
    void onMessage(const TcpConnectionPtr &conn,
                   Buffer *buf,
                   Timestamp tm)
    {
        LOG_INFO << "=============onMessage";
    }

    void onConnection(const TcpConnectionPtr &conn)
    {
        LOG_INFO << "=============onConnection";
    }

private:
    TcpClient _m_client;
    EventLoop *_m_pLoop;
};

int main(int argc, char const *argv[])
{
    /* code */
    // printf("hello\n");
    EventLoop loop;
    EchoClient client(&loop, InetAddress("127.0.0.1", 9000));
    client.connect();
    loop.loop();
    return 0;
}

```

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f0031ada859 in __GI_abort () at abort.c:79
#2  0x00007f0031ada729 in __assert_fail_base (
    fmt=0x7f0031c705b8 "%s%s%s:%u: %s%sUnexpected error: %s.\n%n", 
    assertion=assertion@entry=0x7f0031c6c98a "Invalid argument", 
    file=file@entry=0x55f862bdf3b0 "/home/yqq/mine/muduo/muduo/base/Mutex.h", 
    line=line@entry=151, function=function@entry=0x55f862bdf3f0 "lock")
    at assert.c:92
#3  0x00007f0031aebfa9 in __GI___assert_perror_fail (errnum=<optimized out>, 
    file=file@entry=0x55f862bdf3b0 "/home/yqq/mine/muduo/muduo/base/Mutex.h", 
    line=line@entry=151, function=function@entry=0x55f862bdf3f0 "lock")
    at assert-perr.c:35
#4  0x000055f862bca0b2 in muduo::MutexLock::lock (this=0x55f862bde728)
    at /home/yqq/mine/muduo/muduo/base/Mutex.h:151
#5  muduo::MutexLockGuard::MutexLockGuard (mutex=..., this=<synthetic pointer>)
    at /home/yqq/mine/muduo/muduo/base/Mutex.h:213
#6  muduo::net::EventLoop::queueInLoop(std::function<void ()>) (
    this=0x55f862bde6c0 <__libc_csu_init>, cb=...)
    at /home/yqq/mine/muduo/muduo/net/EventLoop.cc:163
#7  0x000055f862bca1c0 in muduo::net::EventLoop::runInLoop(std::function<void ()>) (
--Type <RET> for more, q to quit, c to continue without paging--
    this=this@entry=0x55f862bde6c0 <__libc_csu_init>, cb=...)
    at /usr/include/c++/9/bits/move.h:182
#8  0x000055f862bd80e7 in muduo::net::Connector::start (this=<optimized out>)
    at /usr/include/c++/9/bits/move.h:74
#9  0x000055f862bcdf50 in muduo::net::TcpClient::connect (this=0x7ffd20c103d8)
    at /usr/include/c++/9/bits/shared_ptr_base.h:1020
#10 0x000055f862bc5dde in EchoClient::connect (this=0x7ffd20c103d0)
    at /home/yqq/mine/muduonotes/10_idleconnections/echo_client.cc:23
#11 0x000055f862bc5909 in main (argc=1, argv=0x7ffd20c105d8)
    at /home/yqq/mine/muduonotes/10_idleconnections/echo_client.cc:50
(gdb) 
```

**Comment by youngqqcn** [comment]
```cpp
EchoClient(EventLoop *pLoop, const InetAddress &addr)
        : _m_pLoop(pLoop),
          _m_client(_m_pLoop, addr, "client")

```

```cpp
EchoClient(EventLoop *pLoop, const InetAddress &addr)
        : _m_pLoop(pLoop),
          _m_client(pLoop, addr, "client")  // instead of  _m_pLoop

```
